#!/usr/bin/env php
<?php

$autoloader = require file_exists(__DIR__.'/vendor/autoload.php') ?  __DIR__.'/vendor/autoload.php' : __DIR__.'/../../autoload.php';
$envdir = file_exists(__DIR__.'/vendor/autoload.php') ? __DIR__ : __DIR__.'/../../..';
$dotenv = \Dotenv\Dotenv::createImmutable($envdir);
$dotenv->load();

if(empty(env('KONG_ADMIN_BASE')) || empty(env('KONG_ADMIN_URI')) || empty(env('KONG_API_KEY'))) {
	throw new \Exception('Kong Gateway Admin URI, BASE or Kong API Key is missing.');
	exit;
}

kong()->testConnection(true);
kong()->consumer()->testConnection(true);
kong()->service()->testConnection(true);
kong()->route()->testConnection(true);
kong()->plugin()->testConnection(true);
kong()->tag()->testConnection(true);
kong()->information()->testConnection(true);
kong()->status()->testConnection(true);
// @todo need to find a way to test the target object. as for now, kiv. 
// kong()->target()->testConnection(true);
kong()->upstream()->testConnection(true);
kong()->certificate()->testConnection(true);
kong()->caCertificate()->testConnection(true);
kong()->sni()->testConnection(true);
kong()->plugin('proxy-cache')->testConnection(true);